name: Unit Test

on: 
  push:
    branches: 
      - develop
  pull_request:
    branches:
      - develop

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: test
      run:
        pip install --user awscli
        export PATH=$PATH:$HOME/.local/bin
        aws s3 cp s3://unexisting
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
    - name: Unit test
      run: ./gradlew test

